name: bitcoindart
description: A dart Bitcoin library for Flutter. BIP32, BIP39, P2PKH integration.
version: 2.2.1
homepage: https://github.com/keybagio/bitcoindart
author: KY <harrykyguo@gmail.com>

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  bech32: ^0.1.2
  bip32: ^1.0.7
  bip39: ^1.0.3
  pointycastle: ^1.0.2
  hex: ^0.1.2
  bs58check: ^1.0.1
  meta: ^1.2.4

dev_dependencies:
  test: ^1.15.4
  pedantic: ^1.9.0
