name: bitcoindart
description: A dart Bitcoin library for Flutter. BIP32, BIP39, P2PKH integration.
version: 3.0.1
homepage: https://github.com/keybagio/bitcoindart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bech32:
    git:
      url: https://github.com/cypherstack/bech32.git
      ref: ea645c864462ed4cee380c806718e0fc3d20bef1
  bip32: ^2.0.0
  bip39: ^1.0.3
  pointycastle: ^3.6.0
  hex: ^0.2.0
  bs58check: ^1.0.1
  meta: ^1.2.4

dev_dependencies:
  test: ^1.15.4
  pedantic: ^1.9.0
